spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lms_auth
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  security:
    user:
      name: admin
      password: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081