spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-ms
          uri: lb://AUTH-MS
          predicates:
            - Path=/api/auth/**
        - id: candidate-ms
          uri: lb://CANDIDATE-MS
          predicates:
            - Path=/api/candidates/**
        - id: status-ms
          uri: lb://STATUS-MS
          predicates:
            - Path=/api/status/**
        - id: document-ms
          uri: lb://DOCUMENT-MS
          predicates:
            - Path=/api/documents/**
        - id: notification-ms
          uri: lb://NOTIFICATION-MS
          predicates:
            - Path=/api/notifications/**

server:
  port: 8222